### ISSUE TITLE
create new branch, commit a file and create a pull request

### ISSUE THREAD

**Issue by schwittlick** [generatorOf/internship#1]
keywords:

    git branch
    pull request

**Comment by generatorOf** [comment]
ich suche erst einmal alles dazu wie pyenv funktioniert

**Comment by generatorOf** [comment]
beim versuch die branch v2 zu pushen, kam folgende Ausgabe:
```fatal: The current branch v2 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin v2
```

**Comment by generatorOf** [comment]
closed with this pull request
https://github.com/generatorOf/internship/pull/3
