### ISSUE TITLE
byobu

### ISSUE THREAD

**Issue by schwittlick** [generatorOf/internship#7]

**Comment by generatorOf** [comment]
is being installed

**Comment by generatorOf** [comment]
on friday, I discovered, that my built-in terminal on my deepin linux have also some usefull functions:--
- for example:
- [x] when i shut `f2+alt` it shows a terminal window on half screen at the top,
- [ ] ok, create new tabs is going over mouseclicking
- [x] but I can switch between the terminal tabs with `ALT+<Number>`

![DeepinScreenshot_20200120113704](https://user-images.githubusercontent.com/44445651/72720539-7c8ebe80-3b7a-11ea-9707-4a90687ea7b6.png)
)
- [ ] nevertheless I will read again the tutorial of **byodu** and will give it a chance to impress me.

**Comment by schwittlick** [comment]
you can close this when you tested it

**Comment by generatorOf** [comment]
ok, there were some short cut conflicts with my linux sistem, but [win]+F2 works for a new Tab Instance in byobu
I will try it out to use it mainly.
